import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Sidebars for the hand-written content under /docs (repo root).
// The generated API sidebar lives in ./sidebars-api.ts (separate docs plugin instance).
const sidebars: SidebarsConfig = {
    architectureSidebar: [{ type: 'autogenerated', dirName: 'framework/architecture' }],
    gameDesignSidebar: [{ type: 'autogenerated', dirName: 'game/design' }],
    gameContentSidebar: [{ type: 'autogenerated', dirName: 'game/content' }],
    tutorialsSidebar: [{ type: 'autogenerated', dirName: 'tutorials' }],
};

export default sidebars;
